# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: business/comment.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from model import model_pb2 as model_dot_model__pb2
import common_pb2 as common__pb2
from business import public_pb2 as business_dot_public__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='business/comment.proto',
  package='duoyu',
  syntax='proto3',
  serialized_pb=_b('\n\x16\x62usiness/comment.proto\x12\x05\x64uoyu\x1a\x11model/model.proto\x1a\x0c\x63ommon.proto\x1a\x15\x62usiness/public.proto\"J\n\x16GetDiaryCommentRequest\x12\x10\n\x08\x64iary_id\x18\x01 \x01(\t\x12\x1e\n\x06\x63ursor\x18\x02 \x01(\x0b\x32\x0e.common.Cursor\"N\n\x18GetCorrectCommentRequest\x12\x12\n\ncorrect_id\x18\x01 \x01(\t\x12\x1e\n\x06\x63ursor\x18\x02 \x01(\x0b\x32\x0e.common.Cursor\"V\n\x12GetCommentResponse\x12 \n\x08\x63omments\x18\x01 \x03(\x0b\x32\x0e.model.Comment\x12\x1e\n\x06\x63ursor\x18\x02 \x01(\x0b\x32\x0e.common.Cursor\"4\n\x11PutCommentRequest\x12\x1f\n\x07\x63omment\x18\x01 \x01(\x0b\x32\x0e.model.Comment\"F\n\x12PutCommentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x1f\n\x07\x63omment\x18\x02 \x01(\x0b\x32\x0e.model.Comment\"*\n\x14\x44\x65leteCommentRequest\x12\x12\n\ncomment_id\x18\x01 \x01(\t\"{\n\x15\x44\x65leteCommentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x31\n\x05\x65rrno\x18\x02 \x01(\x0e\x32\".duoyu.DeleteCommentResponse.Errno\"\x1e\n\x05\x45rrno\x12\x15\n\x11NOT_FOUND_COMMENT\x10\x00\x32\xb3\x03\n\x0e\x43ommentService\x12K\n\x0fgetDiaryComment\x12\x1d.duoyu.GetDiaryCommentRequest\x1a\x19.duoyu.GetCommentResponse\x12O\n\x11getCorrectComment\x12\x1f.duoyu.GetCorrectCommentRequest\x1a\x19.duoyu.GetCommentResponse\x12\x36\n\x0blikeComment\x12\x12.duoyu.LikeRequest\x1a\x13.duoyu.LikeResponse\x12<\n\runlikeComment\x12\x14.duoyu.UnlikeRequest\x1a\x15.duoyu.UnlikeResponse\x12\x41\n\nputComment\x12\x18.duoyu.PutCommentRequest\x1a\x19.duoyu.PutCommentResponse\x12J\n\rdeleteComment\x12\x1b.duoyu.DeleteCommentRequest\x1a\x1c.duoyu.DeleteCommentResponseB \n\x1eme.littlekey.duoyu.model.protob\x06proto3')
  ,
  dependencies=[model_dot_model__pb2.DESCRIPTOR,common__pb2.DESCRIPTOR,business_dot_public__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_DELETECOMMENTRESPONSE_ERRNO = _descriptor.EnumDescriptor(
  name='Errno',
  full_name='duoyu.DeleteCommentResponse.Errno',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOT_FOUND_COMMENT', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=596,
  serialized_end=626,
)
_sym_db.RegisterEnumDescriptor(_DELETECOMMENTRESPONSE_ERRNO)


_GETDIARYCOMMENTREQUEST = _descriptor.Descriptor(
  name='GetDiaryCommentRequest',
  full_name='duoyu.GetDiaryCommentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='diary_id', full_name='duoyu.GetDiaryCommentRequest.diary_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cursor', full_name='duoyu.GetDiaryCommentRequest.cursor', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=163,
)


_GETCORRECTCOMMENTREQUEST = _descriptor.Descriptor(
  name='GetCorrectCommentRequest',
  full_name='duoyu.GetCorrectCommentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='correct_id', full_name='duoyu.GetCorrectCommentRequest.correct_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cursor', full_name='duoyu.GetCorrectCommentRequest.cursor', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=243,
)


_GETCOMMENTRESPONSE = _descriptor.Descriptor(
  name='GetCommentResponse',
  full_name='duoyu.GetCommentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='comments', full_name='duoyu.GetCommentResponse.comments', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cursor', full_name='duoyu.GetCommentResponse.cursor', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=331,
)


_PUTCOMMENTREQUEST = _descriptor.Descriptor(
  name='PutCommentRequest',
  full_name='duoyu.PutCommentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='comment', full_name='duoyu.PutCommentRequest.comment', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=385,
)


_PUTCOMMENTRESPONSE = _descriptor.Descriptor(
  name='PutCommentResponse',
  full_name='duoyu.PutCommentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='duoyu.PutCommentResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='comment', full_name='duoyu.PutCommentResponse.comment', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=457,
)


_DELETECOMMENTREQUEST = _descriptor.Descriptor(
  name='DeleteCommentRequest',
  full_name='duoyu.DeleteCommentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='comment_id', full_name='duoyu.DeleteCommentRequest.comment_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=459,
  serialized_end=501,
)


_DELETECOMMENTRESPONSE = _descriptor.Descriptor(
  name='DeleteCommentResponse',
  full_name='duoyu.DeleteCommentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='duoyu.DeleteCommentResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errno', full_name='duoyu.DeleteCommentResponse.errno', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DELETECOMMENTRESPONSE_ERRNO,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=503,
  serialized_end=626,
)

_GETDIARYCOMMENTREQUEST.fields_by_name['cursor'].message_type = common__pb2._CURSOR
_GETCORRECTCOMMENTREQUEST.fields_by_name['cursor'].message_type = common__pb2._CURSOR
_GETCOMMENTRESPONSE.fields_by_name['comments'].message_type = model_dot_model__pb2._COMMENT
_GETCOMMENTRESPONSE.fields_by_name['cursor'].message_type = common__pb2._CURSOR
_PUTCOMMENTREQUEST.fields_by_name['comment'].message_type = model_dot_model__pb2._COMMENT
_PUTCOMMENTRESPONSE.fields_by_name['comment'].message_type = model_dot_model__pb2._COMMENT
_DELETECOMMENTRESPONSE.fields_by_name['errno'].enum_type = _DELETECOMMENTRESPONSE_ERRNO
_DELETECOMMENTRESPONSE_ERRNO.containing_type = _DELETECOMMENTRESPONSE
DESCRIPTOR.message_types_by_name['GetDiaryCommentRequest'] = _GETDIARYCOMMENTREQUEST
DESCRIPTOR.message_types_by_name['GetCorrectCommentRequest'] = _GETCORRECTCOMMENTREQUEST
DESCRIPTOR.message_types_by_name['GetCommentResponse'] = _GETCOMMENTRESPONSE
DESCRIPTOR.message_types_by_name['PutCommentRequest'] = _PUTCOMMENTREQUEST
DESCRIPTOR.message_types_by_name['PutCommentResponse'] = _PUTCOMMENTRESPONSE
DESCRIPTOR.message_types_by_name['DeleteCommentRequest'] = _DELETECOMMENTREQUEST
DESCRIPTOR.message_types_by_name['DeleteCommentResponse'] = _DELETECOMMENTRESPONSE

GetDiaryCommentRequest = _reflection.GeneratedProtocolMessageType('GetDiaryCommentRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETDIARYCOMMENTREQUEST,
  __module__ = 'business.comment_pb2'
  # @@protoc_insertion_point(class_scope:duoyu.GetDiaryCommentRequest)
  ))
_sym_db.RegisterMessage(GetDiaryCommentRequest)

GetCorrectCommentRequest = _reflection.GeneratedProtocolMessageType('GetCorrectCommentRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETCORRECTCOMMENTREQUEST,
  __module__ = 'business.comment_pb2'
  # @@protoc_insertion_point(class_scope:duoyu.GetCorrectCommentRequest)
  ))
_sym_db.RegisterMessage(GetCorrectCommentRequest)

GetCommentResponse = _reflection.GeneratedProtocolMessageType('GetCommentResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETCOMMENTRESPONSE,
  __module__ = 'business.comment_pb2'
  # @@protoc_insertion_point(class_scope:duoyu.GetCommentResponse)
  ))
_sym_db.RegisterMessage(GetCommentResponse)

PutCommentRequest = _reflection.GeneratedProtocolMessageType('PutCommentRequest', (_message.Message,), dict(
  DESCRIPTOR = _PUTCOMMENTREQUEST,
  __module__ = 'business.comment_pb2'
  # @@protoc_insertion_point(class_scope:duoyu.PutCommentRequest)
  ))
_sym_db.RegisterMessage(PutCommentRequest)

PutCommentResponse = _reflection.GeneratedProtocolMessageType('PutCommentResponse', (_message.Message,), dict(
  DESCRIPTOR = _PUTCOMMENTRESPONSE,
  __module__ = 'business.comment_pb2'
  # @@protoc_insertion_point(class_scope:duoyu.PutCommentResponse)
  ))
_sym_db.RegisterMessage(PutCommentResponse)

DeleteCommentRequest = _reflection.GeneratedProtocolMessageType('DeleteCommentRequest', (_message.Message,), dict(
  DESCRIPTOR = _DELETECOMMENTREQUEST,
  __module__ = 'business.comment_pb2'
  # @@protoc_insertion_point(class_scope:duoyu.DeleteCommentRequest)
  ))
_sym_db.RegisterMessage(DeleteCommentRequest)

DeleteCommentResponse = _reflection.GeneratedProtocolMessageType('DeleteCommentResponse', (_message.Message,), dict(
  DESCRIPTOR = _DELETECOMMENTRESPONSE,
  __module__ = 'business.comment_pb2'
  # @@protoc_insertion_point(class_scope:duoyu.DeleteCommentResponse)
  ))
_sym_db.RegisterMessage(DeleteCommentResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\036me.littlekey.duoyu.model.proto'))
# @@protoc_insertion_point(module_scope)
