# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: business/correct.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from model import model_pb2 as model_dot_model__pb2
import comment_pb2 as comment__pb2
from business import public_pb2 as business_dot_public__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='business/correct.proto',
  package='duoyu',
  syntax='proto3',
  serialized_pb=_b('\n\x16\x62usiness/correct.proto\x12\x05\x64uoyu\x1a\x11model/model.proto\x1a\rcomment.proto\x1a\x15\x62usiness/public.proto\"3\n\x10\x43orrectedRequest\x12\x1f\n\x06\x63ursor\x18\x01 \x01(\x0b\x32\x0f.comment.Cursor\"O\n\x1bGetCorrectedByUserIdRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x1f\n\x06\x63ursor\x18\x02 \x01(\x0b\x32\x0f.comment.Cursor\"V\n\x11\x43orrectedResponse\x12 \n\x08\x63orrects\x18\x01 \x03(\x0b\x32\x0e.model.Correct\x12\x1f\n\x06\x63ursor\x18\x02 \x01(\x0b\x32\x0f.comment.Cursor\"4\n\x11PutCorrectRequest\x12\x1f\n\x07\x63orrect\x18\x01 \x01(\x0b\x32\x0e.model.Correct\"F\n\x12PutCorrectResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x1f\n\x07\x63orrect\x18\x02 \x01(\x0b\x32\x0e.model.Correct\"*\n\x14\x44\x65leteCorrectRequest\x12\x12\n\ncorrect_id\x18\x01 \x01(\t\"{\n\x15\x44\x65leteCorrectResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x31\n\x05\x65rrno\x18\x02 \x01(\x0e\x32\".duoyu.DeleteCorrectResponse.Errno\"\x1e\n\x05\x45rrno\x12\x15\n\x11NOT_FOUND_CORRECT\x10\x00\x32\xb1\x03\n\x0e\x43orrectService\x12\x43\n\x0euserCorrecteds\x12\x17.duoyu.CorrectedRequest\x1a\x18.duoyu.CorrectedResponse\x12U\n\x15getCorrectedsByUserId\x12\".duoyu.GetCorrectedByUserIdRequest\x1a\x18.duoyu.CorrectedResponse\x12\x36\n\x0blikeCorrect\x12\x12.duoyu.LikeRequest\x1a\x13.duoyu.LikeResponse\x12<\n\runlikeCorrect\x12\x14.duoyu.UnlikeRequest\x1a\x15.duoyu.UnlikeResponse\x12\x41\n\nputCorrect\x12\x18.duoyu.PutCorrectRequest\x1a\x19.duoyu.PutCorrectResponse\x12J\n\rdeleteCorrect\x12\x1b.duoyu.DeleteCorrectRequest\x1a\x1c.duoyu.DeleteCorrectResponseB \n\x1eme.littlekey.duoyu.model.protob\x06proto3')
  ,
  dependencies=[model_dot_model__pb2.DESCRIPTOR,comment__pb2.DESCRIPTOR,business_dot_public__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_DELETECORRECTRESPONSE_ERRNO = _descriptor.EnumDescriptor(
  name='Errno',
  full_name='duoyu.DeleteCorrectResponse.Errno',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOT_FOUND_CORRECT', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=575,
  serialized_end=605,
)
_sym_db.RegisterEnumDescriptor(_DELETECORRECTRESPONSE_ERRNO)


_CORRECTEDREQUEST = _descriptor.Descriptor(
  name='CorrectedRequest',
  full_name='duoyu.CorrectedRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cursor', full_name='duoyu.CorrectedRequest.cursor', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=141,
)


_GETCORRECTEDBYUSERIDREQUEST = _descriptor.Descriptor(
  name='GetCorrectedByUserIdRequest',
  full_name='duoyu.GetCorrectedByUserIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='duoyu.GetCorrectedByUserIdRequest.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cursor', full_name='duoyu.GetCorrectedByUserIdRequest.cursor', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=222,
)


_CORRECTEDRESPONSE = _descriptor.Descriptor(
  name='CorrectedResponse',
  full_name='duoyu.CorrectedResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='corrects', full_name='duoyu.CorrectedResponse.corrects', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cursor', full_name='duoyu.CorrectedResponse.cursor', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=310,
)


_PUTCORRECTREQUEST = _descriptor.Descriptor(
  name='PutCorrectRequest',
  full_name='duoyu.PutCorrectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='correct', full_name='duoyu.PutCorrectRequest.correct', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=364,
)


_PUTCORRECTRESPONSE = _descriptor.Descriptor(
  name='PutCorrectResponse',
  full_name='duoyu.PutCorrectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='duoyu.PutCorrectResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='correct', full_name='duoyu.PutCorrectResponse.correct', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=366,
  serialized_end=436,
)


_DELETECORRECTREQUEST = _descriptor.Descriptor(
  name='DeleteCorrectRequest',
  full_name='duoyu.DeleteCorrectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='correct_id', full_name='duoyu.DeleteCorrectRequest.correct_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=438,
  serialized_end=480,
)


_DELETECORRECTRESPONSE = _descriptor.Descriptor(
  name='DeleteCorrectResponse',
  full_name='duoyu.DeleteCorrectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='duoyu.DeleteCorrectResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errno', full_name='duoyu.DeleteCorrectResponse.errno', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DELETECORRECTRESPONSE_ERRNO,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=482,
  serialized_end=605,
)

_CORRECTEDREQUEST.fields_by_name['cursor'].message_type = comment__pb2._CURSOR
_GETCORRECTEDBYUSERIDREQUEST.fields_by_name['cursor'].message_type = comment__pb2._CURSOR
_CORRECTEDRESPONSE.fields_by_name['corrects'].message_type = model_dot_model__pb2._CORRECT
_CORRECTEDRESPONSE.fields_by_name['cursor'].message_type = comment__pb2._CURSOR
_PUTCORRECTREQUEST.fields_by_name['correct'].message_type = model_dot_model__pb2._CORRECT
_PUTCORRECTRESPONSE.fields_by_name['correct'].message_type = model_dot_model__pb2._CORRECT
_DELETECORRECTRESPONSE.fields_by_name['errno'].enum_type = _DELETECORRECTRESPONSE_ERRNO
_DELETECORRECTRESPONSE_ERRNO.containing_type = _DELETECORRECTRESPONSE
DESCRIPTOR.message_types_by_name['CorrectedRequest'] = _CORRECTEDREQUEST
DESCRIPTOR.message_types_by_name['GetCorrectedByUserIdRequest'] = _GETCORRECTEDBYUSERIDREQUEST
DESCRIPTOR.message_types_by_name['CorrectedResponse'] = _CORRECTEDRESPONSE
DESCRIPTOR.message_types_by_name['PutCorrectRequest'] = _PUTCORRECTREQUEST
DESCRIPTOR.message_types_by_name['PutCorrectResponse'] = _PUTCORRECTRESPONSE
DESCRIPTOR.message_types_by_name['DeleteCorrectRequest'] = _DELETECORRECTREQUEST
DESCRIPTOR.message_types_by_name['DeleteCorrectResponse'] = _DELETECORRECTRESPONSE

CorrectedRequest = _reflection.GeneratedProtocolMessageType('CorrectedRequest', (_message.Message,), dict(
  DESCRIPTOR = _CORRECTEDREQUEST,
  __module__ = 'business.correct_pb2'
  # @@protoc_insertion_point(class_scope:duoyu.CorrectedRequest)
  ))
_sym_db.RegisterMessage(CorrectedRequest)

GetCorrectedByUserIdRequest = _reflection.GeneratedProtocolMessageType('GetCorrectedByUserIdRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETCORRECTEDBYUSERIDREQUEST,
  __module__ = 'business.correct_pb2'
  # @@protoc_insertion_point(class_scope:duoyu.GetCorrectedByUserIdRequest)
  ))
_sym_db.RegisterMessage(GetCorrectedByUserIdRequest)

CorrectedResponse = _reflection.GeneratedProtocolMessageType('CorrectedResponse', (_message.Message,), dict(
  DESCRIPTOR = _CORRECTEDRESPONSE,
  __module__ = 'business.correct_pb2'
  # @@protoc_insertion_point(class_scope:duoyu.CorrectedResponse)
  ))
_sym_db.RegisterMessage(CorrectedResponse)

PutCorrectRequest = _reflection.GeneratedProtocolMessageType('PutCorrectRequest', (_message.Message,), dict(
  DESCRIPTOR = _PUTCORRECTREQUEST,
  __module__ = 'business.correct_pb2'
  # @@protoc_insertion_point(class_scope:duoyu.PutCorrectRequest)
  ))
_sym_db.RegisterMessage(PutCorrectRequest)

PutCorrectResponse = _reflection.GeneratedProtocolMessageType('PutCorrectResponse', (_message.Message,), dict(
  DESCRIPTOR = _PUTCORRECTRESPONSE,
  __module__ = 'business.correct_pb2'
  # @@protoc_insertion_point(class_scope:duoyu.PutCorrectResponse)
  ))
_sym_db.RegisterMessage(PutCorrectResponse)

DeleteCorrectRequest = _reflection.GeneratedProtocolMessageType('DeleteCorrectRequest', (_message.Message,), dict(
  DESCRIPTOR = _DELETECORRECTREQUEST,
  __module__ = 'business.correct_pb2'
  # @@protoc_insertion_point(class_scope:duoyu.DeleteCorrectRequest)
  ))
_sym_db.RegisterMessage(DeleteCorrectRequest)

DeleteCorrectResponse = _reflection.GeneratedProtocolMessageType('DeleteCorrectResponse', (_message.Message,), dict(
  DESCRIPTOR = _DELETECORRECTRESPONSE,
  __module__ = 'business.correct_pb2'
  # @@protoc_insertion_point(class_scope:duoyu.DeleteCorrectResponse)
  ))
_sym_db.RegisterMessage(DeleteCorrectResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\036me.littlekey.duoyu.model.proto'))
# @@protoc_insertion_point(module_scope)
