# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comment.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='comment.proto',
  package='comment',
  syntax='proto3',
  serialized_pb=_b('\n\rcomment.proto\x12\x07\x63omment\"F\n\x11PrehashedPassword\x12\x1a\n\x12prehashed_password\x18\x01 \x01(\x0c\x12\x15\n\rprehash_cycle\x18\x02 \x01(\r\"L\n\x06\x43ursor\x12\x11\n\ttimestamp\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\x12\r\n\x05limit\x18\x03 \x01(\x05\x12\x10\n\x08has_more\x18\x04 \x01(\x08\"\r\n\x0bNullMessageB \n\x1eme.littlekey.duoyu.model.protob\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PREHASHEDPASSWORD = _descriptor.Descriptor(
  name='PrehashedPassword',
  full_name='comment.PrehashedPassword',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prehashed_password', full_name='comment.PrehashedPassword.prehashed_password', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prehash_cycle', full_name='comment.PrehashedPassword.prehash_cycle', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=96,
)


_CURSOR = _descriptor.Descriptor(
  name='Cursor',
  full_name='comment.Cursor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='comment.Cursor.timestamp', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='offset', full_name='comment.Cursor.offset', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='limit', full_name='comment.Cursor.limit', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='has_more', full_name='comment.Cursor.has_more', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=174,
)


_NULLMESSAGE = _descriptor.Descriptor(
  name='NullMessage',
  full_name='comment.NullMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=189,
)

DESCRIPTOR.message_types_by_name['PrehashedPassword'] = _PREHASHEDPASSWORD
DESCRIPTOR.message_types_by_name['Cursor'] = _CURSOR
DESCRIPTOR.message_types_by_name['NullMessage'] = _NULLMESSAGE

PrehashedPassword = _reflection.GeneratedProtocolMessageType('PrehashedPassword', (_message.Message,), dict(
  DESCRIPTOR = _PREHASHEDPASSWORD,
  __module__ = 'comment_pb2'
  # @@protoc_insertion_point(class_scope:comment.PrehashedPassword)
  ))
_sym_db.RegisterMessage(PrehashedPassword)

Cursor = _reflection.GeneratedProtocolMessageType('Cursor', (_message.Message,), dict(
  DESCRIPTOR = _CURSOR,
  __module__ = 'comment_pb2'
  # @@protoc_insertion_point(class_scope:comment.Cursor)
  ))
_sym_db.RegisterMessage(Cursor)

NullMessage = _reflection.GeneratedProtocolMessageType('NullMessage', (_message.Message,), dict(
  DESCRIPTOR = _NULLMESSAGE,
  __module__ = 'comment_pb2'
  # @@protoc_insertion_point(class_scope:comment.NullMessage)
  ))
_sym_db.RegisterMessage(NullMessage)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\036me.littlekey.duoyu.model.proto'))
# @@protoc_insertion_point(module_scope)
