// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: business/correct.proto at 10:1
package me.littlekey.duoyu.model.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class CorrectedRequest extends Message<CorrectedRequest, CorrectedRequest.Builder> {
  public static final ProtoAdapter<CorrectedRequest> ADAPTER = new ProtoAdapter_CorrectedRequest();

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 1,
      adapter = "me.littlekey.duoyu.model.proto.Cursor#ADAPTER"
  )
  public final Cursor cursor;

  public CorrectedRequest(Cursor cursor) {
    this(cursor, ByteString.EMPTY);
  }

  public CorrectedRequest(Cursor cursor, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.cursor = cursor;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.cursor = cursor;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof CorrectedRequest)) return false;
    CorrectedRequest o = (CorrectedRequest) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(cursor, o.cursor);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (cursor != null ? cursor.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (cursor != null) builder.append(", cursor=").append(cursor);
    return builder.replace(0, 2, "CorrectedRequest{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<CorrectedRequest, Builder> {
    public Cursor cursor;

    public Builder() {
    }

    public Builder cursor(Cursor cursor) {
      this.cursor = cursor;
      return this;
    }

    @Override
    public CorrectedRequest build() {
      return new CorrectedRequest(cursor, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_CorrectedRequest extends ProtoAdapter<CorrectedRequest> {
    ProtoAdapter_CorrectedRequest() {
      super(FieldEncoding.LENGTH_DELIMITED, CorrectedRequest.class);
    }

    @Override
    public int encodedSize(CorrectedRequest value) {
      return (value.cursor != null ? Cursor.ADAPTER.encodedSizeWithTag(1, value.cursor) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, CorrectedRequest value) throws IOException {
      if (value.cursor != null) Cursor.ADAPTER.encodeWithTag(writer, 1, value.cursor);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public CorrectedRequest decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.cursor(Cursor.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public CorrectedRequest redact(CorrectedRequest value) {
      Builder builder = value.newBuilder();
      if (builder.cursor != null) builder.cursor = Cursor.ADAPTER.redact(builder.cursor);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
