// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: business/correct.proto at 19:1
package me.littlekey.duoyu.model.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

public final class CorrectedResponse extends Message<CorrectedResponse, CorrectedResponse.Builder> {
  public static final ProtoAdapter<CorrectedResponse> ADAPTER = new ProtoAdapter_CorrectedResponse();

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 1,
      adapter = "me.littlekey.duoyu.model.proto.Correct#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<Correct> corrects;

  @WireField(
      tag = 2,
      adapter = "me.littlekey.duoyu.model.proto.Cursor#ADAPTER"
  )
  public final Cursor cursor;

  public CorrectedResponse(List<Correct> corrects, Cursor cursor) {
    this(corrects, cursor, ByteString.EMPTY);
  }

  public CorrectedResponse(List<Correct> corrects, Cursor cursor, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.corrects = Internal.immutableCopyOf("corrects", corrects);
    this.cursor = cursor;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.corrects = Internal.copyOf("corrects", corrects);
    builder.cursor = cursor;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof CorrectedResponse)) return false;
    CorrectedResponse o = (CorrectedResponse) other;
    return unknownFields().equals(o.unknownFields())
        && corrects.equals(o.corrects)
        && Internal.equals(cursor, o.cursor);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + corrects.hashCode();
      result = result * 37 + (cursor != null ? cursor.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (!corrects.isEmpty()) builder.append(", corrects=").append(corrects);
    if (cursor != null) builder.append(", cursor=").append(cursor);
    return builder.replace(0, 2, "CorrectedResponse{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<CorrectedResponse, Builder> {
    public List<Correct> corrects;

    public Cursor cursor;

    public Builder() {
      corrects = Internal.newMutableList();
    }

    public Builder corrects(List<Correct> corrects) {
      Internal.checkElementsNotNull(corrects);
      this.corrects = corrects;
      return this;
    }

    public Builder cursor(Cursor cursor) {
      this.cursor = cursor;
      return this;
    }

    @Override
    public CorrectedResponse build() {
      return new CorrectedResponse(corrects, cursor, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_CorrectedResponse extends ProtoAdapter<CorrectedResponse> {
    ProtoAdapter_CorrectedResponse() {
      super(FieldEncoding.LENGTH_DELIMITED, CorrectedResponse.class);
    }

    @Override
    public int encodedSize(CorrectedResponse value) {
      return Correct.ADAPTER.asRepeated().encodedSizeWithTag(1, value.corrects)
          + (value.cursor != null ? Cursor.ADAPTER.encodedSizeWithTag(2, value.cursor) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, CorrectedResponse value) throws IOException {
      Correct.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.corrects);
      if (value.cursor != null) Cursor.ADAPTER.encodeWithTag(writer, 2, value.cursor);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public CorrectedResponse decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.corrects.add(Correct.ADAPTER.decode(reader)); break;
          case 2: builder.cursor(Cursor.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public CorrectedResponse redact(CorrectedResponse value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.corrects, Correct.ADAPTER);
      if (builder.cursor != null) builder.cursor = Cursor.ADAPTER.redact(builder.cursor);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
