// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: business/user.proto at 9:1
package me.littlekey.duoyu.model.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class CurrentRequest extends Message<CurrentRequest, CurrentRequest.Builder> {
  public static final ProtoAdapter<CurrentRequest> ADAPTER = new ProtoAdapter_CurrentRequest();

  private static final long serialVersionUID = 0L;

  public CurrentRequest() {
    this(ByteString.EMPTY);
  }

  public CurrentRequest(ByteString unknownFields) {
    super(ADAPTER, unknownFields);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof CurrentRequest;
  }

  @Override
  public int hashCode() {
    return unknownFields().hashCode();
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    return builder.replace(0, 2, "CurrentRequest{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<CurrentRequest, Builder> {
    public Builder() {
    }

    @Override
    public CurrentRequest build() {
      return new CurrentRequest(super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_CurrentRequest extends ProtoAdapter<CurrentRequest> {
    ProtoAdapter_CurrentRequest() {
      super(FieldEncoding.LENGTH_DELIMITED, CurrentRequest.class);
    }

    @Override
    public int encodedSize(CurrentRequest value) {
      return value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, CurrentRequest value) throws IOException {
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public CurrentRequest decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public CurrentRequest redact(CurrentRequest value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
