// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: business/user.proto at 12:1
package me.littlekey.duoyu.model.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class CurrentResponse extends Message<CurrentResponse, CurrentResponse.Builder> {
  public static final ProtoAdapter<CurrentResponse> ADAPTER = new ProtoAdapter_CurrentResponse();

  private static final long serialVersionUID = 0L;

  public static final Boolean DEFAULT_SUCCESS = false;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean success;

  @WireField(
      tag = 2,
      adapter = "me.littlekey.duoyu.model.proto.User#ADAPTER"
  )
  public final User user;

  public CurrentResponse(Boolean success, User user) {
    this(success, user, ByteString.EMPTY);
  }

  public CurrentResponse(Boolean success, User user, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.success = success;
    this.user = user;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.success = success;
    builder.user = user;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof CurrentResponse)) return false;
    CurrentResponse o = (CurrentResponse) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(success, o.success)
        && Internal.equals(user, o.user);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (success != null ? success.hashCode() : 0);
      result = result * 37 + (user != null ? user.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (success != null) builder.append(", success=").append(success);
    if (user != null) builder.append(", user=").append(user);
    return builder.replace(0, 2, "CurrentResponse{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<CurrentResponse, Builder> {
    public Boolean success;

    public User user;

    public Builder() {
    }

    public Builder success(Boolean success) {
      this.success = success;
      return this;
    }

    public Builder user(User user) {
      this.user = user;
      return this;
    }

    @Override
    public CurrentResponse build() {
      return new CurrentResponse(success, user, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_CurrentResponse extends ProtoAdapter<CurrentResponse> {
    ProtoAdapter_CurrentResponse() {
      super(FieldEncoding.LENGTH_DELIMITED, CurrentResponse.class);
    }

    @Override
    public int encodedSize(CurrentResponse value) {
      return (value.success != null ? ProtoAdapter.BOOL.encodedSizeWithTag(1, value.success) : 0)
          + (value.user != null ? User.ADAPTER.encodedSizeWithTag(2, value.user) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, CurrentResponse value) throws IOException {
      if (value.success != null) ProtoAdapter.BOOL.encodeWithTag(writer, 1, value.success);
      if (value.user != null) User.ADAPTER.encodeWithTag(writer, 2, value.user);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public CurrentResponse decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.success(ProtoAdapter.BOOL.decode(reader)); break;
          case 2: builder.user(User.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public CurrentResponse redact(CurrentResponse value) {
      Builder builder = value.newBuilder();
      if (builder.user != null) builder.user = User.ADAPTER.redact(builder.user);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
