// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: business/comment.proto at 34:1
package me.littlekey.duoyu.model.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class DeleteCommentRequest extends Message<DeleteCommentRequest, DeleteCommentRequest.Builder> {
  public static final ProtoAdapter<DeleteCommentRequest> ADAPTER = new ProtoAdapter_DeleteCommentRequest();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_COMMENT_ID = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String comment_id;

  public DeleteCommentRequest(String comment_id) {
    this(comment_id, ByteString.EMPTY);
  }

  public DeleteCommentRequest(String comment_id, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.comment_id = comment_id;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.comment_id = comment_id;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof DeleteCommentRequest)) return false;
    DeleteCommentRequest o = (DeleteCommentRequest) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(comment_id, o.comment_id);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (comment_id != null ? comment_id.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (comment_id != null) builder.append(", comment_id=").append(comment_id);
    return builder.replace(0, 2, "DeleteCommentRequest{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<DeleteCommentRequest, Builder> {
    public String comment_id;

    public Builder() {
    }

    public Builder comment_id(String comment_id) {
      this.comment_id = comment_id;
      return this;
    }

    @Override
    public DeleteCommentRequest build() {
      return new DeleteCommentRequest(comment_id, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_DeleteCommentRequest extends ProtoAdapter<DeleteCommentRequest> {
    ProtoAdapter_DeleteCommentRequest() {
      super(FieldEncoding.LENGTH_DELIMITED, DeleteCommentRequest.class);
    }

    @Override
    public int encodedSize(DeleteCommentRequest value) {
      return (value.comment_id != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.comment_id) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, DeleteCommentRequest value) throws IOException {
      if (value.comment_id != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.comment_id);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public DeleteCommentRequest decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.comment_id(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public DeleteCommentRequest redact(DeleteCommentRequest value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
