// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: business/user.proto at 72:1
package me.littlekey.duoyu.model.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

public final class FollowingResponse extends Message<FollowingResponse, FollowingResponse.Builder> {
  public static final ProtoAdapter<FollowingResponse> ADAPTER = new ProtoAdapter_FollowingResponse();

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 1,
      adapter = "me.littlekey.duoyu.model.proto.User#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<User> users;

  public FollowingResponse(List<User> users) {
    this(users, ByteString.EMPTY);
  }

  public FollowingResponse(List<User> users, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.users = Internal.immutableCopyOf("users", users);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.users = Internal.copyOf("users", users);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof FollowingResponse)) return false;
    FollowingResponse o = (FollowingResponse) other;
    return unknownFields().equals(o.unknownFields())
        && users.equals(o.users);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + users.hashCode();
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (!users.isEmpty()) builder.append(", users=").append(users);
    return builder.replace(0, 2, "FollowingResponse{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<FollowingResponse, Builder> {
    public List<User> users;

    public Builder() {
      users = Internal.newMutableList();
    }

    public Builder users(List<User> users) {
      Internal.checkElementsNotNull(users);
      this.users = users;
      return this;
    }

    @Override
    public FollowingResponse build() {
      return new FollowingResponse(users, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_FollowingResponse extends ProtoAdapter<FollowingResponse> {
    ProtoAdapter_FollowingResponse() {
      super(FieldEncoding.LENGTH_DELIMITED, FollowingResponse.class);
    }

    @Override
    public int encodedSize(FollowingResponse value) {
      return User.ADAPTER.asRepeated().encodedSizeWithTag(1, value.users)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, FollowingResponse value) throws IOException {
      User.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.users);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public FollowingResponse decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.users.add(User.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public FollowingResponse redact(FollowingResponse value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.users, User.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
