// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: business/comment.proto at 15:1
package me.littlekey.duoyu.model.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class GetCorrectCommentRequest extends Message<GetCorrectCommentRequest, GetCorrectCommentRequest.Builder> {
  public static final ProtoAdapter<GetCorrectCommentRequest> ADAPTER = new ProtoAdapter_GetCorrectCommentRequest();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_CORRECT_ID = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String correct_id;

  @WireField(
      tag = 2,
      adapter = "me.littlekey.duoyu.model.proto.Cursor#ADAPTER"
  )
  public final Cursor cursor;

  public GetCorrectCommentRequest(String correct_id, Cursor cursor) {
    this(correct_id, cursor, ByteString.EMPTY);
  }

  public GetCorrectCommentRequest(String correct_id, Cursor cursor, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.correct_id = correct_id;
    this.cursor = cursor;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.correct_id = correct_id;
    builder.cursor = cursor;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetCorrectCommentRequest)) return false;
    GetCorrectCommentRequest o = (GetCorrectCommentRequest) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(correct_id, o.correct_id)
        && Internal.equals(cursor, o.cursor);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (correct_id != null ? correct_id.hashCode() : 0);
      result = result * 37 + (cursor != null ? cursor.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (correct_id != null) builder.append(", correct_id=").append(correct_id);
    if (cursor != null) builder.append(", cursor=").append(cursor);
    return builder.replace(0, 2, "GetCorrectCommentRequest{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GetCorrectCommentRequest, Builder> {
    public String correct_id;

    public Cursor cursor;

    public Builder() {
    }

    public Builder correct_id(String correct_id) {
      this.correct_id = correct_id;
      return this;
    }

    public Builder cursor(Cursor cursor) {
      this.cursor = cursor;
      return this;
    }

    @Override
    public GetCorrectCommentRequest build() {
      return new GetCorrectCommentRequest(correct_id, cursor, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetCorrectCommentRequest extends ProtoAdapter<GetCorrectCommentRequest> {
    ProtoAdapter_GetCorrectCommentRequest() {
      super(FieldEncoding.LENGTH_DELIMITED, GetCorrectCommentRequest.class);
    }

    @Override
    public int encodedSize(GetCorrectCommentRequest value) {
      return (value.correct_id != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.correct_id) : 0)
          + (value.cursor != null ? Cursor.ADAPTER.encodedSizeWithTag(2, value.cursor) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, GetCorrectCommentRequest value) throws IOException {
      if (value.correct_id != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.correct_id);
      if (value.cursor != null) Cursor.ADAPTER.encodeWithTag(writer, 2, value.cursor);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetCorrectCommentRequest decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.correct_id(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.cursor(Cursor.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public GetCorrectCommentRequest redact(GetCorrectCommentRequest value) {
      Builder builder = value.newBuilder();
      if (builder.cursor != null) builder.cursor = Cursor.ADAPTER.redact(builder.cursor);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
