// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: business/correct.proto at 14:1
package me.littlekey.duoyu.model.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class GetCorrectedByUserIdRequest extends Message<GetCorrectedByUserIdRequest, GetCorrectedByUserIdRequest.Builder> {
  public static final ProtoAdapter<GetCorrectedByUserIdRequest> ADAPTER = new ProtoAdapter_GetCorrectedByUserIdRequest();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_USER_ID = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String user_id;

  @WireField(
      tag = 2,
      adapter = "me.littlekey.duoyu.model.proto.Cursor#ADAPTER"
  )
  public final Cursor cursor;

  public GetCorrectedByUserIdRequest(String user_id, Cursor cursor) {
    this(user_id, cursor, ByteString.EMPTY);
  }

  public GetCorrectedByUserIdRequest(String user_id, Cursor cursor, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.user_id = user_id;
    this.cursor = cursor;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.user_id = user_id;
    builder.cursor = cursor;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetCorrectedByUserIdRequest)) return false;
    GetCorrectedByUserIdRequest o = (GetCorrectedByUserIdRequest) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(user_id, o.user_id)
        && Internal.equals(cursor, o.cursor);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (user_id != null ? user_id.hashCode() : 0);
      result = result * 37 + (cursor != null ? cursor.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (user_id != null) builder.append(", user_id=").append(user_id);
    if (cursor != null) builder.append(", cursor=").append(cursor);
    return builder.replace(0, 2, "GetCorrectedByUserIdRequest{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GetCorrectedByUserIdRequest, Builder> {
    public String user_id;

    public Cursor cursor;

    public Builder() {
    }

    public Builder user_id(String user_id) {
      this.user_id = user_id;
      return this;
    }

    public Builder cursor(Cursor cursor) {
      this.cursor = cursor;
      return this;
    }

    @Override
    public GetCorrectedByUserIdRequest build() {
      return new GetCorrectedByUserIdRequest(user_id, cursor, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetCorrectedByUserIdRequest extends ProtoAdapter<GetCorrectedByUserIdRequest> {
    ProtoAdapter_GetCorrectedByUserIdRequest() {
      super(FieldEncoding.LENGTH_DELIMITED, GetCorrectedByUserIdRequest.class);
    }

    @Override
    public int encodedSize(GetCorrectedByUserIdRequest value) {
      return (value.user_id != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.user_id) : 0)
          + (value.cursor != null ? Cursor.ADAPTER.encodedSizeWithTag(2, value.cursor) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, GetCorrectedByUserIdRequest value) throws IOException {
      if (value.user_id != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.user_id);
      if (value.cursor != null) Cursor.ADAPTER.encodeWithTag(writer, 2, value.cursor);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetCorrectedByUserIdRequest decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.user_id(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.cursor(Cursor.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public GetCorrectedByUserIdRequest redact(GetCorrectedByUserIdRequest value) {
      Builder builder = value.newBuilder();
      if (builder.cursor != null) builder.cursor = Cursor.ADAPTER.redact(builder.cursor);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
