// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: business/user.proto at 21:1
package me.littlekey.duoyu.model.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireEnum;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class GetUserByIdResponse extends Message<GetUserByIdResponse, GetUserByIdResponse.Builder> {
  public static final ProtoAdapter<GetUserByIdResponse> ADAPTER = new ProtoAdapter_GetUserByIdResponse();

  private static final long serialVersionUID = 0L;

  public static final Boolean DEFAULT_SUCCESS = false;

  public static final Errno DEFAULT_ERRNO = Errno.USER_NOT_FOUND;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean success;

  @WireField(
      tag = 2,
      adapter = "me.littlekey.duoyu.model.proto.User#ADAPTER"
  )
  public final User user;

  @WireField(
      tag = 3,
      adapter = "me.littlekey.duoyu.model.proto.GetUserByIdResponse$Errno#ADAPTER"
  )
  public final Errno errno;

  public GetUserByIdResponse(Boolean success, User user, Errno errno) {
    this(success, user, errno, ByteString.EMPTY);
  }

  public GetUserByIdResponse(Boolean success, User user, Errno errno, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.success = success;
    this.user = user;
    this.errno = errno;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.success = success;
    builder.user = user;
    builder.errno = errno;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetUserByIdResponse)) return false;
    GetUserByIdResponse o = (GetUserByIdResponse) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(success, o.success)
        && Internal.equals(user, o.user)
        && Internal.equals(errno, o.errno);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (success != null ? success.hashCode() : 0);
      result = result * 37 + (user != null ? user.hashCode() : 0);
      result = result * 37 + (errno != null ? errno.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (success != null) builder.append(", success=").append(success);
    if (user != null) builder.append(", user=").append(user);
    if (errno != null) builder.append(", errno=").append(errno);
    return builder.replace(0, 2, "GetUserByIdResponse{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GetUserByIdResponse, Builder> {
    public Boolean success;

    public User user;

    public Errno errno;

    public Builder() {
    }

    public Builder success(Boolean success) {
      this.success = success;
      return this;
    }

    public Builder user(User user) {
      this.user = user;
      return this;
    }

    public Builder errno(Errno errno) {
      this.errno = errno;
      return this;
    }

    @Override
    public GetUserByIdResponse build() {
      return new GetUserByIdResponse(success, user, errno, super.buildUnknownFields());
    }
  }

  public enum Errno implements WireEnum {
    USER_NOT_FOUND(0);

    public static final ProtoAdapter<Errno> ADAPTER = ProtoAdapter.newEnumAdapter(Errno.class);

    private final int value;

    Errno(int value) {
      this.value = value;
    }

    /**
     * Return the constant for {@code value} or null.
     */
    public static Errno fromValue(int value) {
      switch (value) {
        case 0: return USER_NOT_FOUND;
        default: return null;
      }
    }

    @Override
    public int getValue() {
      return value;
    }
  }

  private static final class ProtoAdapter_GetUserByIdResponse extends ProtoAdapter<GetUserByIdResponse> {
    ProtoAdapter_GetUserByIdResponse() {
      super(FieldEncoding.LENGTH_DELIMITED, GetUserByIdResponse.class);
    }

    @Override
    public int encodedSize(GetUserByIdResponse value) {
      return (value.success != null ? ProtoAdapter.BOOL.encodedSizeWithTag(1, value.success) : 0)
          + (value.user != null ? User.ADAPTER.encodedSizeWithTag(2, value.user) : 0)
          + (value.errno != null ? Errno.ADAPTER.encodedSizeWithTag(3, value.errno) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, GetUserByIdResponse value) throws IOException {
      if (value.success != null) ProtoAdapter.BOOL.encodeWithTag(writer, 1, value.success);
      if (value.user != null) User.ADAPTER.encodeWithTag(writer, 2, value.user);
      if (value.errno != null) Errno.ADAPTER.encodeWithTag(writer, 3, value.errno);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetUserByIdResponse decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.success(ProtoAdapter.BOOL.decode(reader)); break;
          case 2: builder.user(User.ADAPTER.decode(reader)); break;
          case 3: {
            try {
              builder.errno(Errno.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public GetUserByIdResponse redact(GetUserByIdResponse value) {
      Builder builder = value.newBuilder();
      if (builder.user != null) builder.user = User.ADAPTER.redact(builder.user);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
