// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: model/model.proto at 78:1
package me.littlekey.duoyu.model.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireEnum;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class Happening extends Message<Happening, Happening.Builder> {
  public static final ProtoAdapter<Happening> ADAPTER = new ProtoAdapter_Happening();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_HAPPENING_ID = "";

  public static final Integer DEFAULT_DATE = 0;

  public static final String DEFAULT_TITLE = "";

  public static final String DEFAULT_CONTENT = "";

  public static final Event DEFAULT_EVENT = Event.LIKE_DIARY;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String happening_id;

  @WireField(
      tag = 2,
      adapter = "me.littlekey.duoyu.model.proto.User#ADAPTER"
  )
  public final User user;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer date;

  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String title;

  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String content;

  @WireField(
      tag = 6,
      adapter = "me.littlekey.duoyu.model.proto.Happening$Event#ADAPTER"
  )
  public final Event event;

  public Happening(String happening_id, User user, Integer date, String title, String content, Event event) {
    this(happening_id, user, date, title, content, event, ByteString.EMPTY);
  }

  public Happening(String happening_id, User user, Integer date, String title, String content, Event event, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.happening_id = happening_id;
    this.user = user;
    this.date = date;
    this.title = title;
    this.content = content;
    this.event = event;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.happening_id = happening_id;
    builder.user = user;
    builder.date = date;
    builder.title = title;
    builder.content = content;
    builder.event = event;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Happening)) return false;
    Happening o = (Happening) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(happening_id, o.happening_id)
        && Internal.equals(user, o.user)
        && Internal.equals(date, o.date)
        && Internal.equals(title, o.title)
        && Internal.equals(content, o.content)
        && Internal.equals(event, o.event);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (happening_id != null ? happening_id.hashCode() : 0);
      result = result * 37 + (user != null ? user.hashCode() : 0);
      result = result * 37 + (date != null ? date.hashCode() : 0);
      result = result * 37 + (title != null ? title.hashCode() : 0);
      result = result * 37 + (content != null ? content.hashCode() : 0);
      result = result * 37 + (event != null ? event.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (happening_id != null) builder.append(", happening_id=").append(happening_id);
    if (user != null) builder.append(", user=").append(user);
    if (date != null) builder.append(", date=").append(date);
    if (title != null) builder.append(", title=").append(title);
    if (content != null) builder.append(", content=").append(content);
    if (event != null) builder.append(", event=").append(event);
    return builder.replace(0, 2, "Happening{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<Happening, Builder> {
    public String happening_id;

    public User user;

    public Integer date;

    public String title;

    public String content;

    public Event event;

    public Builder() {
    }

    public Builder happening_id(String happening_id) {
      this.happening_id = happening_id;
      return this;
    }

    public Builder user(User user) {
      this.user = user;
      return this;
    }

    public Builder date(Integer date) {
      this.date = date;
      return this;
    }

    public Builder title(String title) {
      this.title = title;
      return this;
    }

    public Builder content(String content) {
      this.content = content;
      return this;
    }

    public Builder event(Event event) {
      this.event = event;
      return this;
    }

    @Override
    public Happening build() {
      return new Happening(happening_id, user, date, title, content, event, super.buildUnknownFields());
    }
  }

  public enum Event implements WireEnum {
    LIKE_DIARY(0),

    LIKE_CORRECT(1),

    PUBLISH_DIARY(2),

    PUT_CORRECT(3);

    public static final ProtoAdapter<Event> ADAPTER = ProtoAdapter.newEnumAdapter(Event.class);

    private final int value;

    Event(int value) {
      this.value = value;
    }

    /**
     * Return the constant for {@code value} or null.
     */
    public static Event fromValue(int value) {
      switch (value) {
        case 0: return LIKE_DIARY;
        case 1: return LIKE_CORRECT;
        case 2: return PUBLISH_DIARY;
        case 3: return PUT_CORRECT;
        default: return null;
      }
    }

    @Override
    public int getValue() {
      return value;
    }
  }

  private static final class ProtoAdapter_Happening extends ProtoAdapter<Happening> {
    ProtoAdapter_Happening() {
      super(FieldEncoding.LENGTH_DELIMITED, Happening.class);
    }

    @Override
    public int encodedSize(Happening value) {
      return (value.happening_id != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.happening_id) : 0)
          + (value.user != null ? User.ADAPTER.encodedSizeWithTag(2, value.user) : 0)
          + (value.date != null ? ProtoAdapter.INT32.encodedSizeWithTag(3, value.date) : 0)
          + (value.title != null ? ProtoAdapter.STRING.encodedSizeWithTag(4, value.title) : 0)
          + (value.content != null ? ProtoAdapter.STRING.encodedSizeWithTag(5, value.content) : 0)
          + (value.event != null ? Event.ADAPTER.encodedSizeWithTag(6, value.event) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, Happening value) throws IOException {
      if (value.happening_id != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.happening_id);
      if (value.user != null) User.ADAPTER.encodeWithTag(writer, 2, value.user);
      if (value.date != null) ProtoAdapter.INT32.encodeWithTag(writer, 3, value.date);
      if (value.title != null) ProtoAdapter.STRING.encodeWithTag(writer, 4, value.title);
      if (value.content != null) ProtoAdapter.STRING.encodeWithTag(writer, 5, value.content);
      if (value.event != null) Event.ADAPTER.encodeWithTag(writer, 6, value.event);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public Happening decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.happening_id(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.user(User.ADAPTER.decode(reader)); break;
          case 3: builder.date(ProtoAdapter.INT32.decode(reader)); break;
          case 4: builder.title(ProtoAdapter.STRING.decode(reader)); break;
          case 5: builder.content(ProtoAdapter.STRING.decode(reader)); break;
          case 6: {
            try {
              builder.event(Event.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public Happening redact(Happening value) {
      Builder builder = value.newBuilder();
      if (builder.user != null) builder.user = User.ADAPTER.redact(builder.user);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
