// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: model/model.proto at 9:1
package me.littlekey.duoyu.model.proto;

import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum Language implements WireEnum {
  CHINESE(0),

  ENGLISH(1),

  JAPANESE(2),

  RUSSIAN(3),

  KOREAN(4);

  public static final ProtoAdapter<Language> ADAPTER = ProtoAdapter.newEnumAdapter(Language.class);

  private final int value;

  Language(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static Language fromValue(int value) {
    switch (value) {
      case 0: return CHINESE;
      case 1: return ENGLISH;
      case 2: return JAPANESE;
      case 3: return RUSSIAN;
      case 4: return KOREAN;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }
}
