// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: business/account.proto at 9:1
package me.littlekey.duoyu.model.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class LoginRequest extends Message<LoginRequest, LoginRequest.Builder> {
  public static final ProtoAdapter<LoginRequest> ADAPTER = new ProtoAdapter_LoginRequest();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_EMAIL = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String email;

  @WireField(
      tag = 2,
      adapter = "me.littlekey.duoyu.model.proto.PrehashedPassword#ADAPTER"
  )
  public final PrehashedPassword password;

  public LoginRequest(String email, PrehashedPassword password) {
    this(email, password, ByteString.EMPTY);
  }

  public LoginRequest(String email, PrehashedPassword password, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.email = email;
    this.password = password;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.email = email;
    builder.password = password;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof LoginRequest)) return false;
    LoginRequest o = (LoginRequest) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(email, o.email)
        && Internal.equals(password, o.password);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (email != null ? email.hashCode() : 0);
      result = result * 37 + (password != null ? password.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (email != null) builder.append(", email=").append(email);
    if (password != null) builder.append(", password=").append(password);
    return builder.replace(0, 2, "LoginRequest{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<LoginRequest, Builder> {
    public String email;

    public PrehashedPassword password;

    public Builder() {
    }

    public Builder email(String email) {
      this.email = email;
      return this;
    }

    public Builder password(PrehashedPassword password) {
      this.password = password;
      return this;
    }

    @Override
    public LoginRequest build() {
      return new LoginRequest(email, password, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_LoginRequest extends ProtoAdapter<LoginRequest> {
    ProtoAdapter_LoginRequest() {
      super(FieldEncoding.LENGTH_DELIMITED, LoginRequest.class);
    }

    @Override
    public int encodedSize(LoginRequest value) {
      return (value.email != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.email) : 0)
          + (value.password != null ? PrehashedPassword.ADAPTER.encodedSizeWithTag(2, value.password) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, LoginRequest value) throws IOException {
      if (value.email != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.email);
      if (value.password != null) PrehashedPassword.ADAPTER.encodeWithTag(writer, 2, value.password);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public LoginRequest decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.email(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.password(PrehashedPassword.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public LoginRequest redact(LoginRequest value) {
      Builder builder = value.newBuilder();
      if (builder.password != null) builder.password = PrehashedPassword.ADAPTER.redact(builder.password);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
