// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: business/account.proto at 24:1
package me.littlekey.duoyu.model.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class LogoutRequest extends Message<LogoutRequest, LogoutRequest.Builder> {
  public static final ProtoAdapter<LogoutRequest> ADAPTER = new ProtoAdapter_LogoutRequest();

  private static final long serialVersionUID = 0L;

  public LogoutRequest() {
    this(ByteString.EMPTY);
  }

  public LogoutRequest(ByteString unknownFields) {
    super(ADAPTER, unknownFields);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof LogoutRequest;
  }

  @Override
  public int hashCode() {
    return unknownFields().hashCode();
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    return builder.replace(0, 2, "LogoutRequest{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<LogoutRequest, Builder> {
    public Builder() {
    }

    @Override
    public LogoutRequest build() {
      return new LogoutRequest(super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_LogoutRequest extends ProtoAdapter<LogoutRequest> {
    ProtoAdapter_LogoutRequest() {
      super(FieldEncoding.LENGTH_DELIMITED, LogoutRequest.class);
    }

    @Override
    public int encodedSize(LogoutRequest value) {
      return value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, LogoutRequest value) throws IOException {
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public LogoutRequest decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public LogoutRequest redact(LogoutRequest value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
