// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: model/model.proto at 6:1
package me.littlekey.duoyu.model.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class Model extends Message<Model, Model.Builder> {
  public static final ProtoAdapter<Model> ADAPTER = new ProtoAdapter_Model();

  private static final long serialVersionUID = 0L;

  public Model() {
    this(ByteString.EMPTY);
  }

  public Model(ByteString unknownFields) {
    super(ADAPTER, unknownFields);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof Model;
  }

  @Override
  public int hashCode() {
    return unknownFields().hashCode();
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    return builder.replace(0, 2, "Model{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<Model, Builder> {
    public Builder() {
    }

    @Override
    public Model build() {
      return new Model(super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_Model extends ProtoAdapter<Model> {
    ProtoAdapter_Model() {
      super(FieldEncoding.LENGTH_DELIMITED, Model.class);
    }

    @Override
    public int encodedSize(Model value) {
      return value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, Model value) throws IOException {
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public Model decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public Model redact(Model value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
