// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: model/model.proto at 40:1
package me.littlekey.duoyu.model.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

public final class Profile extends Message<Profile, Profile.Builder> {
  public static final ProtoAdapter<Profile> ADAPTER = new ProtoAdapter_Profile();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_NICKNAME = "";

  public static final String DEFAULT_REGION = "";

  public static final String DEFAULT_INTRODUCE = "";

  public static final String DEFAULT_AVATAR = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String nickname;

  @WireField(
      tag = 2,
      adapter = "me.littlekey.duoyu.model.proto.Language#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<Language> native_language;

  @WireField(
      tag = 3,
      adapter = "me.littlekey.duoyu.model.proto.Language#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<Language> target_language;

  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String region;

  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String introduce;

  @WireField(
      tag = 6,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String avatar;

  public Profile(String nickname, List<Language> native_language, List<Language> target_language, String region, String introduce, String avatar) {
    this(nickname, native_language, target_language, region, introduce, avatar, ByteString.EMPTY);
  }

  public Profile(String nickname, List<Language> native_language, List<Language> target_language, String region, String introduce, String avatar, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.nickname = nickname;
    this.native_language = Internal.immutableCopyOf("native_language", native_language);
    this.target_language = Internal.immutableCopyOf("target_language", target_language);
    this.region = region;
    this.introduce = introduce;
    this.avatar = avatar;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.nickname = nickname;
    builder.native_language = Internal.copyOf("native_language", native_language);
    builder.target_language = Internal.copyOf("target_language", target_language);
    builder.region = region;
    builder.introduce = introduce;
    builder.avatar = avatar;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Profile)) return false;
    Profile o = (Profile) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(nickname, o.nickname)
        && native_language.equals(o.native_language)
        && target_language.equals(o.target_language)
        && Internal.equals(region, o.region)
        && Internal.equals(introduce, o.introduce)
        && Internal.equals(avatar, o.avatar);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (nickname != null ? nickname.hashCode() : 0);
      result = result * 37 + native_language.hashCode();
      result = result * 37 + target_language.hashCode();
      result = result * 37 + (region != null ? region.hashCode() : 0);
      result = result * 37 + (introduce != null ? introduce.hashCode() : 0);
      result = result * 37 + (avatar != null ? avatar.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (nickname != null) builder.append(", nickname=").append(nickname);
    if (!native_language.isEmpty()) builder.append(", native_language=").append(native_language);
    if (!target_language.isEmpty()) builder.append(", target_language=").append(target_language);
    if (region != null) builder.append(", region=").append(region);
    if (introduce != null) builder.append(", introduce=").append(introduce);
    if (avatar != null) builder.append(", avatar=").append(avatar);
    return builder.replace(0, 2, "Profile{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<Profile, Builder> {
    public String nickname;

    public List<Language> native_language;

    public List<Language> target_language;

    public String region;

    public String introduce;

    public String avatar;

    public Builder() {
      native_language = Internal.newMutableList();
      target_language = Internal.newMutableList();
    }

    public Builder nickname(String nickname) {
      this.nickname = nickname;
      return this;
    }

    public Builder native_language(List<Language> native_language) {
      Internal.checkElementsNotNull(native_language);
      this.native_language = native_language;
      return this;
    }

    public Builder target_language(List<Language> target_language) {
      Internal.checkElementsNotNull(target_language);
      this.target_language = target_language;
      return this;
    }

    public Builder region(String region) {
      this.region = region;
      return this;
    }

    public Builder introduce(String introduce) {
      this.introduce = introduce;
      return this;
    }

    public Builder avatar(String avatar) {
      this.avatar = avatar;
      return this;
    }

    @Override
    public Profile build() {
      return new Profile(nickname, native_language, target_language, region, introduce, avatar, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_Profile extends ProtoAdapter<Profile> {
    ProtoAdapter_Profile() {
      super(FieldEncoding.LENGTH_DELIMITED, Profile.class);
    }

    @Override
    public int encodedSize(Profile value) {
      return (value.nickname != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.nickname) : 0)
          + Language.ADAPTER.asRepeated().encodedSizeWithTag(2, value.native_language)
          + Language.ADAPTER.asRepeated().encodedSizeWithTag(3, value.target_language)
          + (value.region != null ? ProtoAdapter.STRING.encodedSizeWithTag(4, value.region) : 0)
          + (value.introduce != null ? ProtoAdapter.STRING.encodedSizeWithTag(5, value.introduce) : 0)
          + (value.avatar != null ? ProtoAdapter.STRING.encodedSizeWithTag(6, value.avatar) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, Profile value) throws IOException {
      if (value.nickname != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.nickname);
      Language.ADAPTER.asRepeated().encodeWithTag(writer, 2, value.native_language);
      Language.ADAPTER.asRepeated().encodeWithTag(writer, 3, value.target_language);
      if (value.region != null) ProtoAdapter.STRING.encodeWithTag(writer, 4, value.region);
      if (value.introduce != null) ProtoAdapter.STRING.encodeWithTag(writer, 5, value.introduce);
      if (value.avatar != null) ProtoAdapter.STRING.encodeWithTag(writer, 6, value.avatar);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public Profile decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.nickname(ProtoAdapter.STRING.decode(reader)); break;
          case 2: {
            try {
              builder.native_language.add(Language.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 3: {
            try {
              builder.target_language.add(Language.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 4: builder.region(ProtoAdapter.STRING.decode(reader)); break;
          case 5: builder.introduce(ProtoAdapter.STRING.decode(reader)); break;
          case 6: builder.avatar(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public Profile redact(Profile value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
