// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: business/comment.proto at 29:1
package me.littlekey.duoyu.model.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class PutCommentResponse extends Message<PutCommentResponse, PutCommentResponse.Builder> {
  public static final ProtoAdapter<PutCommentResponse> ADAPTER = new ProtoAdapter_PutCommentResponse();

  private static final long serialVersionUID = 0L;

  public static final Boolean DEFAULT_SUCCESS = false;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean success;

  @WireField(
      tag = 2,
      adapter = "me.littlekey.duoyu.model.proto.Comment#ADAPTER"
  )
  public final Comment comment;

  public PutCommentResponse(Boolean success, Comment comment) {
    this(success, comment, ByteString.EMPTY);
  }

  public PutCommentResponse(Boolean success, Comment comment, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.success = success;
    this.comment = comment;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.success = success;
    builder.comment = comment;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PutCommentResponse)) return false;
    PutCommentResponse o = (PutCommentResponse) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(success, o.success)
        && Internal.equals(comment, o.comment);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (success != null ? success.hashCode() : 0);
      result = result * 37 + (comment != null ? comment.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (success != null) builder.append(", success=").append(success);
    if (comment != null) builder.append(", comment=").append(comment);
    return builder.replace(0, 2, "PutCommentResponse{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PutCommentResponse, Builder> {
    public Boolean success;

    public Comment comment;

    public Builder() {
    }

    public Builder success(Boolean success) {
      this.success = success;
      return this;
    }

    public Builder comment(Comment comment) {
      this.comment = comment;
      return this;
    }

    @Override
    public PutCommentResponse build() {
      return new PutCommentResponse(success, comment, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PutCommentResponse extends ProtoAdapter<PutCommentResponse> {
    ProtoAdapter_PutCommentResponse() {
      super(FieldEncoding.LENGTH_DELIMITED, PutCommentResponse.class);
    }

    @Override
    public int encodedSize(PutCommentResponse value) {
      return (value.success != null ? ProtoAdapter.BOOL.encodedSizeWithTag(1, value.success) : 0)
          + (value.comment != null ? Comment.ADAPTER.encodedSizeWithTag(2, value.comment) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PutCommentResponse value) throws IOException {
      if (value.success != null) ProtoAdapter.BOOL.encodeWithTag(writer, 1, value.success);
      if (value.comment != null) Comment.ADAPTER.encodeWithTag(writer, 2, value.comment);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PutCommentResponse decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.success(ProtoAdapter.BOOL.decode(reader)); break;
          case 2: builder.comment(Comment.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PutCommentResponse redact(PutCommentResponse value) {
      Builder builder = value.newBuilder();
      if (builder.comment != null) builder.comment = Comment.ADAPTER.redact(builder.comment);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
