// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: business/diary.proto at 46:1
package me.littlekey.duoyu.model.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class PutDiaryResponse extends Message<PutDiaryResponse, PutDiaryResponse.Builder> {
  public static final ProtoAdapter<PutDiaryResponse> ADAPTER = new ProtoAdapter_PutDiaryResponse();

  private static final long serialVersionUID = 0L;

  public static final Boolean DEFAULT_SUCCESS = false;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean success;

  @WireField(
      tag = 2,
      adapter = "me.littlekey.duoyu.model.proto.Diary#ADAPTER"
  )
  public final Diary diary;

  public PutDiaryResponse(Boolean success, Diary diary) {
    this(success, diary, ByteString.EMPTY);
  }

  public PutDiaryResponse(Boolean success, Diary diary, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.success = success;
    this.diary = diary;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.success = success;
    builder.diary = diary;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PutDiaryResponse)) return false;
    PutDiaryResponse o = (PutDiaryResponse) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(success, o.success)
        && Internal.equals(diary, o.diary);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (success != null ? success.hashCode() : 0);
      result = result * 37 + (diary != null ? diary.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (success != null) builder.append(", success=").append(success);
    if (diary != null) builder.append(", diary=").append(diary);
    return builder.replace(0, 2, "PutDiaryResponse{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PutDiaryResponse, Builder> {
    public Boolean success;

    public Diary diary;

    public Builder() {
    }

    public Builder success(Boolean success) {
      this.success = success;
      return this;
    }

    public Builder diary(Diary diary) {
      this.diary = diary;
      return this;
    }

    @Override
    public PutDiaryResponse build() {
      return new PutDiaryResponse(success, diary, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PutDiaryResponse extends ProtoAdapter<PutDiaryResponse> {
    ProtoAdapter_PutDiaryResponse() {
      super(FieldEncoding.LENGTH_DELIMITED, PutDiaryResponse.class);
    }

    @Override
    public int encodedSize(PutDiaryResponse value) {
      return (value.success != null ? ProtoAdapter.BOOL.encodedSizeWithTag(1, value.success) : 0)
          + (value.diary != null ? Diary.ADAPTER.encodedSizeWithTag(2, value.diary) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PutDiaryResponse value) throws IOException {
      if (value.success != null) ProtoAdapter.BOOL.encodeWithTag(writer, 1, value.success);
      if (value.diary != null) Diary.ADAPTER.encodeWithTag(writer, 2, value.diary);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PutDiaryResponse decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.success(ProtoAdapter.BOOL.decode(reader)); break;
          case 2: builder.diary(Diary.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PutDiaryResponse redact(PutDiaryResponse value) {
      Builder builder = value.newBuilder();
      if (builder.diary != null) builder.diary = Diary.ADAPTER.redact(builder.diary);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
