// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: business/diary.proto at 42:1
package me.littlekey.duoyu.model.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class PutDiaryRequest extends Message<PutDiaryRequest, PutDiaryRequest.Builder> {
  public static final ProtoAdapter<PutDiaryRequest> ADAPTER = new ProtoAdapter_PutDiaryRequest();

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 1,
      adapter = "me.littlekey.duoyu.model.proto.Diary#ADAPTER"
  )
  public final Diary diary;

  public PutDiaryRequest(Diary diary) {
    this(diary, ByteString.EMPTY);
  }

  public PutDiaryRequest(Diary diary, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.diary = diary;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.diary = diary;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PutDiaryRequest)) return false;
    PutDiaryRequest o = (PutDiaryRequest) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(diary, o.diary);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (diary != null ? diary.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (diary != null) builder.append(", diary=").append(diary);
    return builder.replace(0, 2, "PutDiaryRequest{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PutDiaryRequest, Builder> {
    public Diary diary;

    public Builder() {
    }

    public Builder diary(Diary diary) {
      this.diary = diary;
      return this;
    }

    @Override
    public PutDiaryRequest build() {
      return new PutDiaryRequest(diary, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PutDiaryRequest extends ProtoAdapter<PutDiaryRequest> {
    ProtoAdapter_PutDiaryRequest() {
      super(FieldEncoding.LENGTH_DELIMITED, PutDiaryRequest.class);
    }

    @Override
    public int encodedSize(PutDiaryRequest value) {
      return (value.diary != null ? Diary.ADAPTER.encodedSizeWithTag(1, value.diary) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PutDiaryRequest value) throws IOException {
      if (value.diary != null) Diary.ADAPTER.encodeWithTag(writer, 1, value.diary);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PutDiaryRequest decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.diary(Diary.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PutDiaryRequest redact(PutDiaryRequest value) {
      Builder builder = value.newBuilder();
      if (builder.diary != null) builder.diary = Diary.ADAPTER.redact(builder.diary);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
