// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: business/user.proto at 100:1
package me.littlekey.duoyu.model.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

public final class TimelineResponse extends Message<TimelineResponse, TimelineResponse.Builder> {
  public static final ProtoAdapter<TimelineResponse> ADAPTER = new ProtoAdapter_TimelineResponse();

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 1,
      adapter = "me.littlekey.duoyu.model.proto.Happening#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<Happening> happenings;

  public TimelineResponse(List<Happening> happenings) {
    this(happenings, ByteString.EMPTY);
  }

  public TimelineResponse(List<Happening> happenings, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.happenings = Internal.immutableCopyOf("happenings", happenings);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.happenings = Internal.copyOf("happenings", happenings);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof TimelineResponse)) return false;
    TimelineResponse o = (TimelineResponse) other;
    return unknownFields().equals(o.unknownFields())
        && happenings.equals(o.happenings);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + happenings.hashCode();
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (!happenings.isEmpty()) builder.append(", happenings=").append(happenings);
    return builder.replace(0, 2, "TimelineResponse{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<TimelineResponse, Builder> {
    public List<Happening> happenings;

    public Builder() {
      happenings = Internal.newMutableList();
    }

    public Builder happenings(List<Happening> happenings) {
      Internal.checkElementsNotNull(happenings);
      this.happenings = happenings;
      return this;
    }

    @Override
    public TimelineResponse build() {
      return new TimelineResponse(happenings, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_TimelineResponse extends ProtoAdapter<TimelineResponse> {
    ProtoAdapter_TimelineResponse() {
      super(FieldEncoding.LENGTH_DELIMITED, TimelineResponse.class);
    }

    @Override
    public int encodedSize(TimelineResponse value) {
      return Happening.ADAPTER.asRepeated().encodedSizeWithTag(1, value.happenings)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, TimelineResponse value) throws IOException {
      Happening.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.happenings);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public TimelineResponse decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.happenings.add(Happening.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public TimelineResponse redact(TimelineResponse value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.happenings, Happening.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
