// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: business/user.proto at 108:1
package me.littlekey.duoyu.model.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireEnum;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class UploadImageResponse extends Message<UploadImageResponse, UploadImageResponse.Builder> {
  public static final ProtoAdapter<UploadImageResponse> ADAPTER = new ProtoAdapter_UploadImageResponse();

  private static final long serialVersionUID = 0L;

  public static final Boolean DEFAULT_SUCCESS = false;

  public static final String DEFAULT_IMAGE_ID = "";

  public static final Errno DEFAULT_ERRNO = Errno.UNKNOWN;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean success;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String image_id;

  @WireField(
      tag = 3,
      adapter = "me.littlekey.duoyu.model.proto.UploadImageResponse$Errno#ADAPTER"
  )
  public final Errno errno;

  public UploadImageResponse(Boolean success, String image_id, Errno errno) {
    this(success, image_id, errno, ByteString.EMPTY);
  }

  public UploadImageResponse(Boolean success, String image_id, Errno errno, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.success = success;
    this.image_id = image_id;
    this.errno = errno;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.success = success;
    builder.image_id = image_id;
    builder.errno = errno;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof UploadImageResponse)) return false;
    UploadImageResponse o = (UploadImageResponse) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(success, o.success)
        && Internal.equals(image_id, o.image_id)
        && Internal.equals(errno, o.errno);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (success != null ? success.hashCode() : 0);
      result = result * 37 + (image_id != null ? image_id.hashCode() : 0);
      result = result * 37 + (errno != null ? errno.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (success != null) builder.append(", success=").append(success);
    if (image_id != null) builder.append(", image_id=").append(image_id);
    if (errno != null) builder.append(", errno=").append(errno);
    return builder.replace(0, 2, "UploadImageResponse{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<UploadImageResponse, Builder> {
    public Boolean success;

    public String image_id;

    public Errno errno;

    public Builder() {
    }

    public Builder success(Boolean success) {
      this.success = success;
      return this;
    }

    public Builder image_id(String image_id) {
      this.image_id = image_id;
      return this;
    }

    public Builder errno(Errno errno) {
      this.errno = errno;
      return this;
    }

    @Override
    public UploadImageResponse build() {
      return new UploadImageResponse(success, image_id, errno, super.buildUnknownFields());
    }
  }

  public enum Errno implements WireEnum {
    UNKNOWN(0),

    IMAGE_TOO_LARGE(1),

    UPLOAD_FAILURE(2);

    public static final ProtoAdapter<Errno> ADAPTER = ProtoAdapter.newEnumAdapter(Errno.class);

    private final int value;

    Errno(int value) {
      this.value = value;
    }

    /**
     * Return the constant for {@code value} or null.
     */
    public static Errno fromValue(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return IMAGE_TOO_LARGE;
        case 2: return UPLOAD_FAILURE;
        default: return null;
      }
    }

    @Override
    public int getValue() {
      return value;
    }
  }

  private static final class ProtoAdapter_UploadImageResponse extends ProtoAdapter<UploadImageResponse> {
    ProtoAdapter_UploadImageResponse() {
      super(FieldEncoding.LENGTH_DELIMITED, UploadImageResponse.class);
    }

    @Override
    public int encodedSize(UploadImageResponse value) {
      return (value.success != null ? ProtoAdapter.BOOL.encodedSizeWithTag(1, value.success) : 0)
          + (value.image_id != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.image_id) : 0)
          + (value.errno != null ? Errno.ADAPTER.encodedSizeWithTag(3, value.errno) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, UploadImageResponse value) throws IOException {
      if (value.success != null) ProtoAdapter.BOOL.encodeWithTag(writer, 1, value.success);
      if (value.image_id != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.image_id);
      if (value.errno != null) Errno.ADAPTER.encodeWithTag(writer, 3, value.errno);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public UploadImageResponse decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.success(ProtoAdapter.BOOL.decode(reader)); break;
          case 2: builder.image_id(ProtoAdapter.STRING.decode(reader)); break;
          case 3: {
            try {
              builder.errno(Errno.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public UploadImageResponse redact(UploadImageResponse value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
