// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: business/user.proto at 104:1
package me.littlekey.duoyu.model.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class UploadImageRequest extends Message<UploadImageRequest, UploadImageRequest.Builder> {
  public static final ProtoAdapter<UploadImageRequest> ADAPTER = new ProtoAdapter_UploadImageRequest();

  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_IMAGE = ByteString.EMPTY;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES"
  )
  public final ByteString image;

  public UploadImageRequest(ByteString image) {
    this(image, ByteString.EMPTY);
  }

  public UploadImageRequest(ByteString image, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.image = image;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.image = image;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof UploadImageRequest)) return false;
    UploadImageRequest o = (UploadImageRequest) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(image, o.image);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (image != null ? image.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (image != null) builder.append(", image=").append(image);
    return builder.replace(0, 2, "UploadImageRequest{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<UploadImageRequest, Builder> {
    public ByteString image;

    public Builder() {
    }

    public Builder image(ByteString image) {
      this.image = image;
      return this;
    }

    @Override
    public UploadImageRequest build() {
      return new UploadImageRequest(image, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_UploadImageRequest extends ProtoAdapter<UploadImageRequest> {
    ProtoAdapter_UploadImageRequest() {
      super(FieldEncoding.LENGTH_DELIMITED, UploadImageRequest.class);
    }

    @Override
    public int encodedSize(UploadImageRequest value) {
      return (value.image != null ? ProtoAdapter.BYTES.encodedSizeWithTag(1, value.image) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, UploadImageRequest value) throws IOException {
      if (value.image != null) ProtoAdapter.BYTES.encodeWithTag(writer, 1, value.image);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public UploadImageRequest decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.image(ProtoAdapter.BYTES.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public UploadImageRequest redact(UploadImageRequest value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
